### PR TITLE
[#114] Do not access the location in the background

### LINKED ISSUE #114: Location accessed in background warning
When the app is opened in the background, some OS might display a similar warning:

grafik

We should try to eliminate background location access so we don't appear to be data miners 😉

### PR DESCRIPTION
**Pull request by juliaringler**
* Changed the Android compileSdkVersion to 29 which now has a seperate permission for background access.

### CODE REVIEW

**Comment by juliaringler** [comment]
@Johannes11833 Could you test on ios?
@ConstantinB9 Does this fix your bug?

**Comment by Johannes11833** [comment]
> @Johannes11833 Could you test on ios?

This was never an issue on iOS bc it never offered GPS access in background. But the new code still works fine on iOS :)

**Comment by Johannes11833** [comment]
Also you should probably adjust the locationPermissionLevel in the permission check in the Tutorial as well

**Comment by juliaringler** [comment]
> Also you should probably adjust the locationPermissionLevel in the permission check in the Tutorial as well

Good point, updated :)

**Review by Johannes11833 — APPROVED** [review]

**Comment by ConstantinB9** [comment]
Appears to have fixed the issue. Did not get notified anymore 👍

**Pull request merged**
