### PR TITLE
[#97] Persist Reservations, Part 1

### PR DESCRIPTION
**Pull request by juliaringler**
* Persisted the list of reservations
* Added restoring the reservations on startup
* Renamed Locations und Reservations to LocationsResponse and ReservationsReponse and moved to http_responses folder

### CODE REVIEW

**Review by ConstantinB9 — COMMENTED** [review]
When opening without active reservations, I got the 'no-connection-screen' although I am online

grafik

**Comment by Johannes11833** [comment]
That already sometimes happened previously to this pr when hot reloading/ restarting. Does it always occur now?

> When opening without active reservations, I got the 'no-connection-screen' although I am online
> 
> grafik

**Comment by ConstantinB9** [comment]
> That already sometimes happened previously to this pr when hot reloading/ restarting. Does it always occur now?

it always does for me, even when re-installing the app. Had a look for the debug output:
```
I/flutter (29443): Loading reservations ...
I/flutter (29443): getReservations: success
I/flutter (29443): Could not retrieve any reservations.
```

**Comment by ConstantinB9** [comment]
Ok, so the try block from the reservations_bloc.dart:

https://github.com/SafeMarket-WirVsVirus/frontend-enduser/blob/2152d545981447c058535aa083125e6dbc042272/lib/bloc/reservations_bloc.dart#L67-L74

fails due to a `NoSuchMethodError` from here

https://github.com/SafeMarket-WirVsVirus/frontend-enduser/blob/2152d545981447c058535aa083125e6dbc042272/lib/repository/reservations_repository.dart#L115-L116

Ultimately resulting in the state being `ReservationsLoadFail`

Edit: found it 😄

**Comment by juliaringler** [comment]
> Ok, so the try block from the reservations_bloc.dart:
> 
> https://github.com/SafeMarket-WirVsVirus/frontend-enduser/blob/2152d545981447c058535aa083125e6dbc042272/lib/bloc/reservations_bloc.dart#L67-L74
> 
> fails due to a `NoSuchMethodError` from here
> 
> https://github.com/SafeMarket-WirVsVirus/frontend-enduser/blob/2152d545981447c058535aa083125e6dbc042272/lib/repository/reservations_repository.dart#L115-L116
> 
> Ultimately resulting in the state being `ReservationsLoadFail`
> 
> Edit: found it 😄

:D Weird, that it did not occur when I tested it … Hot Reload seems to be tricky sometimes

**Review by ConstantinB9 — APPROVED** [review]

**Review by Johannes11833 — APPROVED** [review]
Works on my iPhone 👍

**Pull request merged**
